# Refer ./setup/baseConfig.yaml for full set of config parameters

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - stream
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

stream:
  block-size-mb: 8
  max-buffers: 64
  buffer-size-mb: 36

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: <ACCOUNT_NAME>
  account-key: <ACCOUNT_KEY>
  endpoint: https://<ACCOUNT_NAME>.blob.core.windows.net
  mode: key
  container: <CONTAINER_NAME>